version: "3.3"
services:
  mysql-server:
    build: mysql-server
    container_name: mysql-server
    expose:
      - "3306"
    env_file:
      - zabbix.env
    volumes:
      - zabbix_mysql_data:/var/lib/mysql
    deploy:
      replicas: 1
    restart: on-failure
          
  zabbix-java-gateway:
    build: zabbix-java-gateway
    container_name: zabbix-java-gateway
    expose:
      - "10052"
    env_file:
      - zabbix.env
    environment:
      - ZBX_DEBUGLEVEL=info
    deploy:
      replicas: 1
      
  zabbix-server-mysql:
    build: zabbix-server-mysql
    container_name: zabbix-server-mysql
    ports:
      - "10051:10051"
    env_file:
      - zabbix.env
    environment:
      - ZBX_DEBUGLEVEL=3
    volumes:
      - zabbix_server_data:/var/lib/zabbix
    depends_on:
      - mysql-server
    links:
      - mysql-server:mysql
      - zabbix-java-gateway:gateway
    deploy:
      replicas: 1
      
  zabbix-web-nginx-mysql:
    build: zabbix-web-nginx-mysql
    container_name: zabbix-web-nginx-mysql
    ports:
      - "8080:80"
    env_file:
      - zabbix.env
    depends_on:
      - mysql-server
      - zabbix-server-mysql
    links:
      - mysql-server:mysql
      - zabbix-java-gateway:gateway
      - zabbix-server-mysql:zabbix-server
      
    deploy:
      replicas: 1
      

volumes:
        zabbix_mysql_data:
        zabbix_server_data:
        


